# swagger.yaml
openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
  description: Your API Description
paths:
  /example:
    get:
      summary: Get an example
      responses:
        '200':
          description: Successful response
