name: Deploy Supabase on Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_STG }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD_STG }}
      PROJECT_ID: uwzgscaxncunqjcsuaib

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase db push --include-all
