name: run test on pull request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          for package in classroomio-com dashboard docs; do
            if [ -f "app/$package/package.json" ]; then
              cd "app/$package"
              npm test
              cd -
            fi
          done
